<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [31]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [32]:
data = pd.read_csv('https://code.s3.yandex.net/datasets/insurance.csv')
data


Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0       1     41.0   49600.0            1                  0
1       0     46.0   38000.0            1                  1
2       0     29.0   21000.0            0                  0
3       0     21.0   41700.0            2                  0
4       1     28.0   26100.0            0                  0
...   ...      ...       ...          ...                ...
4995    0     28.0   35700.0            2                  0
4996    0     34.0   52400.0            1                  0
4997    0     20.0   33900.0            2                  0
4998    1     22.0   32700.0            3                  0
4999    1     28.0   40600.0            1                  0

[5000 rows x 5 columns]

Итак, в таблице 5 столбцов.

- Пол, 
- Возраст,
- Зарплата,
- Члены семьи,
- Страховые выплаты.

In [33]:
data.isna().sum()#Проверим наличие в данных пропущенных значений.

Пол                  0
Возраст              0
Зарплата             0
Члены семьи          0
Страховые выплаты    0
dtype: int64

In [34]:
data.duplicated().sum()#Проверим наличие в данных дубликатов

153

In [35]:
data.drop_duplicates(inplace=True)#Удалим дубликаты
data.duplicated().sum()

0

In [36]:
data.info()#вывдем информаци о датасете

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4847 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                4847 non-null   int64  
 1   Возраст            4847 non-null   float64
 2   Зарплата           4847 non-null   float64
 3   Члены семьи        4847 non-null   int64  
 4   Страховые выплаты  4847 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 227.2 KB


In [37]:
data['Пол'].unique()#посмотрим на уникальные значения

array([1, 0])

In [38]:
data['Возраст'].sort_values().unique()#посмотрим на уникальные значения

array([18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.,
       31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
       44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55., 56.,
       57., 58., 59., 60., 61., 62., 65.])

In [39]:
data['Зарплата'].sort_values().unique()#посмотрим на уникальные значения

array([ 5300.,  6000.,  7400.,  8900.,  9800., 10000., 10600., 10800.,
       11000., 11200., 11300., 12200., 12900., 13000., 13200., 13300.,
       13400., 13500., 13800., 13900., 14100., 14300., 14400., 14500.,
       14600., 14700., 15000., 15100., 15200., 15600., 15700., 15900.,
       16000., 16200., 16300., 16400., 16500., 16600., 16700., 17000.,
       17100., 17300., 17400., 17500., 17600., 17700., 17800., 17900.,
       18100., 18200., 18300., 18400., 18600., 18700., 18800., 18900.,
       19000., 19100., 19200., 19300., 19400., 19600., 19700., 19900.,
       20000., 20100., 20200., 20300., 20400., 20500., 20600., 20700.,
       20800., 20900., 21000., 21100., 21200., 21300., 21400., 21500.,
       21600., 21700., 21800., 21900., 22000., 22100., 22200., 22300.,
       22500., 22600., 22700., 22800., 22900., 23000., 23100., 23200.,
       23300., 23400., 23500., 23600., 23700., 23800., 23900., 24000.,
       24100., 24200., 24300., 24400., 24500., 24600., 24700., 24800.,
      

In [40]:
data['Страховые выплаты'].sort_values().unique()#посмотрим на уникальные значения

array([0, 1, 2, 3, 4, 5])

Вывод: 

Итак, в таблице 5 столбцов.

- Пол, 
- Возраст,
- Зарплата,
- Члены семьи,
- Страховые выплаты.

В таблице удалены дубликаты.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — обратимая матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии?

**Ответ:** согласно математическим преобразованиям не изменится.


**Обоснование:** 

Исходя из написанного выше:

$$ a = X(X^T X)^{-1} X^T y $$

Домножим формулу обучения на обратимую матрицу P и обозначим как w1

$$ w1 = ((XP)^T XP)^{-1} (XP)^T y $$

домножим формулу предсказания на обратимую матрицу P и обозначим эту формулу как а1

$$ a1 = XP * w1 $$

тогда

$$ a1 = XP ((XP)^T * XP)^{-1} (XP)^T y $$

$$
((XP)^T * XP)^{-1} = (P^TX^TXP)^{-1} = (P^T(X^TX)P)^{-1} = (X^TXP)^{-1} * (P^T)^{-1} = P^{-1} * (X^TX)^{-1} * (P^T)^{-1}
$$
$$
a1 = XP* P^{-1} * (X^TX)^{-1} * (P^T)^{-1} * P^TX^T * y = X * (X^TX)^{-1} * X^T * y
$$

В данной формуле $ Р , Р^T $ являются квадратными. Для квадратных матриц умножение матрицы на обратную матрицу равно единичной матрице. 

Для сокращения применим следующие свойства матриц:

$$ (AB)^{-1} = B^{-1} A^{-1} $$

$$A A^{-1} = E $$

Таким образом, применим указанное к данной формуле и получим:

$$ a1 = X(X^T X)^{-1} X^T y $$

таким образом:

$$ a1 = a $$

## Алгоритм преобразования

**Алгоритм**

Проверим на практике предыдущий шаг.  
Создадим обратимую квадратную матрицу: 

In [41]:
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']

In [42]:
det = 0 # создадим цикл для генерирования матрицы и проверки ее обратимости.
P = 0
while(det == 0):
    P = np.random.normal(size=(features.shape[1],features.shape[1]))
    det = np.linalg.det(P)
det

-4.861918170731533

Чтобы обосновать, что качество линейной регрессии не изменится, рассчитаем а и а1 на наших данных.

**Обоснование**

In [43]:
w = np.linalg.inv(np.dot(features.T,features)).dot(features.T).dot(target)

In [44]:
a = features.dot(w)

In [45]:
w1 = np.linalg.inv(np.dot(features.dot(P).T,features.dot(P))).dot(features.dot(P).T).dot(target)

In [46]:
a1 = features.dot(P).dot(w1)

In [47]:
np.allclose(a,a1,atol=1e-4)

True

при этом

In [48]:
np.allclose(a,a1,atol=1e-5)

True

**Вывод**  
таким образом, получили, что a и a1 равны до 4 знака.

## Проверка алгоритма

 Создадим модель линейной регрессии до преобразования и посчитаем метрику R2

In [49]:
model = LinearRegression()

model.fit(features, target)

predictions = model.predict(features)

print('Значение R2:', r2_score(target,predictions))

Значение R2: 0.4302010044852066


Умножим исходные признаки на обратимую матрицу и на основе полученных значений вновь посчитаем метрику R2

In [50]:
features_new =features @ P
features_new

0             1             2            3
0     54903.418757  -9741.563827  19126.396972 -7741.555984
1     42081.623720  -7463.302412  14614.781464 -5916.514823
2     23259.928918  -4123.744018   8067.576701 -3266.165025
3     46141.585942  -8191.001065  16113.723014 -6522.738239
4     28898.937969  -5125.693688  10048.481360 -4066.828608
...            ...           ...           ...          ...
4995  39515.582897  -7012.888867  13769.116470 -5573.737672
4996  57990.214349 -10290.803207  20229.406858 -8189.151371
4997  37514.771247  -6659.388883  13091.889958 -5299.484293
4998  36191.444576  -6425.624135  12621.760997 -5107.809532
4999  44934.141683  -7974.241210  15670.343899 -6342.362022

[4847 rows x 4 columns]

In [51]:
model = LinearRegression()

model.fit(features_new, target)

predictions = model.predict(features_new)

print('Значение R2 по новым признакам:', r2_score(target,predictions))

Значение R2 по новым признакам: 0.4302010044852037


**Вывод**  
Таким образом, при разработке метода преобразования данных, чтобы по ним было сложно восстановить персональную информацию, установлено следующее:
1. В качестве преобразования принято умножение на квадратную обратимую матрицу.  
Согласно математическим преобразованиям матрица до преобразования (а) равна преобразованной матрице (а1).   
При этом при проверке на практике установлено, что a и a1 равны только до 4 знака.
2. Корректность работы проверена метрикой R2  
При этом, при преобразовании качество модели незначительно (на 14 знаке после запятой) улучшилось.

